### ISSUE TITLE
Doesn't compile for Java 5

### ISSUE THREAD

**Issue by Spottedleaf** [LaxWasHere/AntiBot#2]
I saw this pr, https://github.com/LaxWasHere/AntiBot/pull/1 and thought that it was dumb that it was rejected because it was not Java 5 compatible, as this codebase in its current state is not Java 5 compatible. 

https://github.com/LaxWasHere/AntiBot/blob/master/src/main/java/net/poweredbyscience/antibot/AntiBot.java#L23 can only be compiled for Java 7.

My Windows 95 server cannot run Java 7 and I'd like this plugin to be written in Java 5 for my sake.

**Comment by LaxWasHere** [comment]
pr or shutup
